package com.assignment1.DevicesAndShelves.Models;

import lombok.*;

import java.time.ZonedDateTime;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShelfPosition {
    private String shelfPositionId;    // UUID string generated by Neo4j randomUUID()
    private String deviceId;           // Reference to parent device
    private Integer positionIndex;     // Position index (1..n within a device)
    private Boolean isOccupied;        // Whether a shelf is placed in this position
    private Boolean isDeleted;         // Soft delete flag
    private ZonedDateTime createdAt;   // Audit timestamp - when position was created
    private ZonedDateTime updatedAt;   // Audit timestamp - when position was last modified

    // Helper to map from Neo4j Node
    public static ShelfPosition from(org.neo4j.driver.types.Node n) {
        ShelfPosition sp = new ShelfPosition();
        sp.setShelfPositionId(n.get("shelfPositionId").asString());
        sp.setDeviceId(n.get("deviceId").asString(null));
        sp.setPositionIndex(n.get("positionIndex").asInt(0));
        sp.setIsOccupied(n.get("isOccupied").asBoolean(false));
        sp.setIsDeleted(n.get("isDeleted").asBoolean(false));

        if (!n.get("createdAt").isNull()) {
            sp.setCreatedAt(n.get("createdAt").asZonedDateTime());
        }
        if (!n.get("updatedAt").isNull()) {
            sp.setUpdatedAt(n.get("updatedAt").asZonedDateTime());
        }
        return sp;
    }
}
