package com.assignment1.DevicesAndShelves.Models;

import lombok.*;

import java.time.ZonedDateTime;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShelfPosition {
    private String shelfPositionId;    // UUID string generated by Neo4j randomUUID()
    private String deviceId;           // Reference to parent device
    private String shelfId;            // Reference to placed shelf (if occupied)
    private String shelfName;          // Name of the shelf placed in this position (for easy display)
    private Integer index;     // Position index (1..n within a device)
    private Boolean isOccupied;        // Whether a shelf is placed in this position
    private Boolean isDeleted;         // Soft delete flag
    private ZonedDateTime createdAt;   // Audit timestamp - when position was created
    private ZonedDateTime updatedAt;   // Audit timestamp - when position was last modified

    // Helper to map from Neo4j Node using builder pattern
    public static ShelfPosition from(org.neo4j.driver.types.Node n) {
        return ShelfPosition.builder()
                .shelfPositionId(n.get("shelfPositionId").asString())
                .deviceId(n.get("deviceId").asString(null))
                .shelfId(n.get("shelfId").asString(null))
                .shelfName(n.get("shelfName").asString(null))
                .index(n.get("index").asInt(0))
                .isOccupied(n.get("isOccupied").asBoolean(false))
                .isDeleted(n.get("isDeleted").asBoolean(false))
                .createdAt(n.get("createdAt").isNull() ? null : n.get("createdAt").asZonedDateTime())
                .updatedAt(n.get("updatedAt").isNull() ? null : n.get("updatedAt").asZonedDateTime())
                .build();
    }
}
